name: Generate a build and push to another branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Push to Build Branch
        uses: s0/git-publish-subdir-action@develop
        with:
          directory: build
          branch: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
